package utility;

public enum Commands {
    NEXT, GETPOSITIONS, GETTUNNEL, GETSTATION, GETSTATUS, START, ADDTRAIN, MOVE, DELETETUNNEL, SETTUNNEL, SETSWITCH, EXIT,
    AUTOMODE, MANUALMODE, LOGON, LOGOFF
}
