package utility;

public enum Commands {
    NEXT, GETPOSITIONS, GETTUNNELS, GETSTATIONS, GETSTATUS, START, ADDTRAIN, MOVE, DELETETUNNEL, SETTUNNEL, SETSWITCH,
    AUTOMODE, MANUALMODE, LOGON, LOGOFF
}
